### ISSUE TITLE
List of Posts

### ISSUE THREAD

**Issue by zamukaev** [zamukaev/recap-project#1]
##List of Posts

##Value Proposition

- As a ...
- I want to ...
- in order to ...

##Description

- Scribble, design, or text
- Make sure you scribble "real" proportions.

##Acceptance criteria

- [ ] What happens when an entry is empty?
- [ ] How should something behave?
- [ ] What is the text of an alert?

##Tasks

- [ ] List the tasks that need to be performed within the dev team
- [ ] Create branch
- [ ] Write tests
- [ ] Generate dummy-data
- [ ] If it's the first user story: Global styles

**Comment by supernova-97** [comment]
Good start! Maybe check the spelling again for better readability. :)

**Comment by LuYujin9** [comment]
Ich finde, es ist toll

**Comment by PReichetanz** [comment]
Hi Muslim,

a really good start for your user story! 🎉

💬 Let's discuss some issues which came to my mind while reading:

## General

## Value Proposition
- Please mind the grammar to be clear here: "As a user, I want to see a list of posts in order to read them."

## Description
I think some parts are too much for the first story:
- the header with Home button, search and login,
- the views and comment functions on each posts
- pagination.
Please consider to move these things to different user stories each.

## Acceptance Criteria
- The details page should be its own user story.

## Tasks

**Comment by Efendi5** [comment]
Really good !

**Comment by PReichetanz** [comment]
Hi Muslim,

very nice rework!

Just one minor thing: Please remove the two ACs
- [ ] Each card is clickable, clicking on it will open a details page
- [ ] The details page should be its own user story.

They should not be part of this story (but I had fun reading them :D ).

**Comment by zamukaev** [comment]
ok thank
