### ISSUE TITLE
create a post

### ISSUE THREAD

**Issue by zamukaev** [zamukaev/recap-project#3]
## Value Proposition

- As a  User  I want to see a add post page in order to create a post

## Description

![Image](https://user-images.githubusercontent.com/79673748/227494451-dd305e06-af7f-4f6b-b285-89bc749d0e4d.png)

## Acceptance criteria

- [ ] The page has a button "upload"
- [ ] The page has two inputs for title and text
- [ ] The page has a button wich create a post 

## Tasks

- [ ] Create the add post page
- [ ] Create the "upload" button,
- [ ] Create the "Add a post" button
- [ ] Write test
- [ ] Add to App

**Comment by salaos** [comment]
Nice one! I have some thoughts:

- is there a default picture, before the new picture is uploaded?
- maybe a "Neuer Beitrag" headline would be helpful / more accessible
